highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /posts/:year/:month/:day/:title.html
port: 3000
safe: true

plugins:
  - jemoji
  - jekyll-seo-tag

url: https://www.clareliguori.com/
baseurl: ''
sourceurl: https://github.com/clareliguori/clareliguori.github.io
title: Clare Liguori
author:
  name: Clare Liguori
  url: https://www.clareliguori.com/
  twitter: clare_liguori
  title: Principal Software Engineer
description: Personal website
avatar: profile.png
email: hello@clareliguori.com
github: clareliguori
twitter:
  username: clare_liguori
  card: summary
linkedin: clareliguori
youtube: PLIF3k1ZrFvz15EXnfVR12qCbgfLqgG3Wa
google_analytics: UA-20185599-1
social:
  name: Clare Liguori
  links:
    - https://twitter.com/clare_liguori
    - https://www.linkedin.com/in/clareliguori
    - https://github.com/clareliguori

# needed for travis-ci build
exclude: [vendor]