# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /posts/:year/:month/:day/:title.html
port: 3000
safe: true

plugins:
  - jemoji
  - jekyll-seo-tag

# edit here to achieve your personal greatness
url: https://www.clareliguori.com/
baseurl: ''
sourceurl: https://github.com/clareliguori/clareliguori.github.io
title: Clare Liguori
author: Clare Liguori
authortitle: Principal Software Engineer
description: Personal website
avatar: profile.png
email: hello@clareliguori.com
github: clareliguori
twitter: clare_liguori
linkedin: clareliguori
youtube: PLIF3k1ZrFvz15EXnfVR12qCbgfLqgG3Wa
google_analytics: UA-20185599-1

# needed for travis-ci build
exclude: [vendor]