# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://clareliguori.github.io/
baseurl: /clareliguori-dot-com/
title: Clare Liguori
author: Clare Liguori
description: Personal website
#avatar: profile.png
email: hello@clareliguori.com
github: clareliguori
twitter: clare_liguori
linkedin: clareliguori
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
google_analytics: UA-20185599-1


# needed for travis-ci build
exclude: [vendor]
