on:
  [pull_request, push]

name: Check

jobs:
  check:
    name: Build Jekyll site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
    - run: |
        bundle install
        jekyll build
      env:
        NOKOGIRI_USE_SYSTEM_LIBRARIES: true
